# Generated by Django 4.0.6 on 2022-08-19 01:51

import apps.productos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.productos.models.product_directory_path),
        ),
    ]
